<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 */
?>

<div class="pp-buttons-container">
    <button type="button" onclick="window.location='<?= $block->getUrl('mfgeoip/maxmind/update') ?>'">
        <span><span><span><?= $block->escapeHtml(_('Update MaxMind GeoIP Data Base')); ?></span></span></span>
    </button>
</div>
